name: renovation_core
description: The missing SDK developers have been longing for to interact with Frappe/ERPNext
version: 1.2.2
homepage: https://github.com/leam-tech/renovation_core.dart

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  http: ^0.12.0
  json_annotation: ^3.0.0
  rxdart: ^0.23.1
  socket_io_client: ^0.9.8
  dio: ^3.0.8
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1
  path: ^1.6.4
  logger: ^0.8.3
  meta: ^1.1.8
  enum_to_string: ^1.0.9
  pedantic: ^1.8.0
  zxcvbn: ^0.0.1

dev_dependencies:
  test: ^1.12.0
  build_runner: ^1.7.4
  json_serializable: ^3.0.0
